# Generated by Django 3.2.8 on 2021-10-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=10, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
