# Generated by Django 3.2.8 on 2021-10-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_last_login'),
        ('local', '0002_reclamos_personal_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaHoraLocal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agenda', models.DateField()),
                ('hora_agenda', models.TimeField()),
                ('preba', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local')),
            ],
        ),
    ]
