# Generated by Django 3.2.8 on 2021-10-21 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_last_login'),
        ('local', '0003_agendahoralocal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendahoralocal',
            name='preba',
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.CreateModel(
            name='ControlAforoLocal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local')),
            ],
        ),
    ]
