# Generated by Django 3.2.8 on 2021-10-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_auto_20211020_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlaforolocal',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='controlaforolocal',
            name='id_local',
        ),
        migrations.RemoveField(
            model_name='reclamos',
            name='id_local',
        ),
        migrations.RemoveField(
            model_name='reclamos',
            name='id_tipo',
        ),
        migrations.RemoveField(
            model_name='reclamos',
            name='personal_asignado',
        ),
        migrations.DeleteModel(
            name='AgendaHoraLocal',
        ),
        migrations.DeleteModel(
            name='ControlAforoLocal',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Reclamos',
        ),
        migrations.DeleteModel(
            name='TipoReclamo',
        ),
    ]
